### ISSUE TITLE
[Q] Any breaking change while migrating from V2 webpack to V3 vite?

### ISSUE THREAD

**Issue by Raj00377** [enuchi/React-Google-Apps-Script#223]

**Comment by enuchi** [comment]
If you want to migrate existing projects I recommend you stay with a fresh clone and copy your existing react app code and server code into the fresh clone, rather than trying to update your old repo.

There are lots of tiny updates so it would be easier to migrate like that.

Note as mentioned in another issue, custom function autocomplete is not yet supported.

Open an issue if something is not working.

**Comment by Raj00377** [comment]
Sure, Thanks.
