### ISSUE TITLE
Install npm packages for serverside 

### ISSUE THREAD

**Issue by kickbox** [enuchi/React-Google-Apps-Script#41]
How can I install node packages like `axios` and make it run on the server side of Google App script?

So far I am able to install packages for the client side. How do I install packages for the server side?

**Comment by enuchi** [comment]
You can't install node packages on the server unfortunately. Google Apps Script doesn't actually run node, it's just a javascript engine.

If you want to make http requests from the server you'll need to use Google Apps Script's UrlFetchApp service:
https://developers.google.com/apps-script/reference/url-fetch/url-fetch-app#fetch(String,Object)

**Comment by kickbox** [comment]
Hi @enuchi, thanks for getting back. Since App Script uses V8 runtime, can I install any package and run within the server environment? My use case goes beyond the `axios` example, sorry for not making it clear. Another example would be `slack api` - https://www.npmjs.com/package/slack.

**Comment by enuchi** [comment]
No @kickbox, I don't think the slack api won't work, since it is intended to run in node and expects the node libraries to be available. If you want to make HTTP requests, for instance for a slack integration, you'll have to use the UrlFetchApp service.

V8 runtime does not mean it is running node on the server. It is just a javascript engine that can process javascript code. The Google Apps Script environment does not include all the features that node does.

By the way, certain npm packages that don't have any external dependencies might work, for instance `lodash` or `moment.js` or other packages like that that are written in pure javascript. Try it out and let me know if you have any luck!

**Comment by kickbox** [comment]
Thanks @enuchi, that makes sense. How should O go about installing a package like `mement.js` for serverside? Would creating a local clone be the best option?

**Comment by kickbox** [comment]
Installing moment.js is easy, just had to put the entire source code in a directory and reference it. Generally I think anything that requires npm and has dependencies in package.json wont work.
