### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by ralphilius** [enuchi/React-Google-Apps-Script#49]
Do you intend to add Typescript to this project? `clasp` already supports this already. 

Thanks for this great project!

**Comment by enuchi** [comment]
Thanks, hope this project has been useful for you.

Not sure I will add typescript into the demo app, since not all users will be familiar or would want to use it. I am redoing the docs right now though, and would be happy to include a section on how to implement typescript if a user wanted to.

Looking at how `clasp` does it, they are using a `ts2gas` package that just converts the typescript code as a string to gas-compatible code right before pushing. I think for this project, since webpack is being used, it would make more sense to just add the `typescript` and `ts-loader` packages and add a rule to the webpack config as described here: https://webpack.js.org/guides/typescript/

That way you could also use typescript for the client-side React code. Does that make sense to you too @ralphilius ?

**Comment by ralphilius** [comment]
Yes. That would be great. Thanks @enuchi

**Comment by RCRJ** [comment]
I'm really fortunate this issue is on your mind, I just started trying to use an external component that uses typescript. Would really appreciate someone else's expertise making sure webpack is configured correctly for that. 

Thanks a lot @enuchi, this project has been extremely useful!

**Comment by enuchi** [comment]
Hi @ralphilius @RCRJ , I've just done a major update for the repo, and included support for typescript. [One of the files in the demo now uses typescript](https://github.com/enuchi/React-Google-Apps-Script/blob/master/src/client/dialog-demo-bootstrap/components/FormInput.tsx), and it seems to work well. If you get a chance, please take a look and see if you have any issues.

**Comment by ralphilius** [comment]
Hi @enuchi, this is just about time for my new project. I'll use it and give feedback. In meantime, for getting started guide what do you think if we turn this repo into a template?

**Comment by enuchi** [comment]
Not sure what you mean @ralphilius. What would a template look like?

**Comment by ralphilius** [comment]
@enuchi This is what I mean: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-from-a-template

**Comment by enuchi** [comment]
Yup, just updated the settings @ralphilius

**Comment by enuchi** [comment]
Hey @ralphilius , going to close this since it's been a couple months. Reopen if you have issues with typescript.
