### ISSUE TITLE
Move focus back to Slides app

### ISSUE THREAD

**Issue by poorawaste** [enuchi/React-Google-Apps-Script#60]
Hi,
I'm trying to build a Slides extension with your wonderful Template. Thank you for that.
I am running into an issue. After I execute a serverFunction I would like to move the focus programmatically to the Slides app so that I can have the ability to undo using shortcut(command + z) right away if I need to. I can't find a way to do that.
I am able to do that when I run the below from an extension written directly in Googles Script Editor.
`google.script.host.editor.focus()`

Any help would be appreciated.

**Comment by enuchi** [comment]
Hmm that's strange -- there should be no difference. I was just able to trigger focus in the Sheets demo app I included, but I needed to change the line below in the server code to use `showModelessDialog()` instead of `showModalDialog`.
https://github.com/enuchi/React-Google-Apps-Script/blob/2721e3405378249d5a24374d39a02cd17146261e/src/server/ui.js#L15

Modeless dialogs let you interact with the main page behind it: https://developers.google.com/apps-script/reference/base/ui#showModelessDialog(Object,String)

Also, the official documentation for `script.host.editor.focus` specifies only "Google Docs, Sheets, or Forms," and not Slides. Assume it would work the same way in Slides though if you say it has worked for you.
https://developers.google.com/apps-script/guides/html/reference/host#index.html_1

**Comment by poorawaste** [comment]
Thanks for the quick response. However that isn’t my issue. My bad, I should've been clearer in my question. Here’s a slightly detailed explanation:
I’ve built a sidebar addon with your template. Overall it’s working great. I have a “left align” button that runs a server side command to align all selected items to the left. Also working great. But if I were to hit “command z” it doesn’t undo the alignment. That’s because the last place I clicked was in the sidebar addon on the button. I am forced to click back in the document to execute an undo. I resolved that in my previous script written in Google Apps Script by running `google.script.host.editor.focus()`. It would programmatically move the focus back to the Slides document. 
That is where the issue is. I can’t seem to find a way to do that in this template.
I hope that clarifies the issue. 
Thank you again.

**Comment by enuchi** [comment]
Have you tried adding the focus command in your button onClick handler? I would do something like:
```
<button
  onClick={() => {
     serverFunctions.runSomeServerFunction()
        .then(() => google.script.host.editor.focus());
   }}
/>
```

**Comment by poorawaste** [comment]
It worked!
It's weird because I had tried that before and it didn't work. I also tried async/await and it hadn't. After further testing I realized that `google.script.host.editor.focus()` only works after deploying the files. Not during the local development using the `npm run start` command.
Thank you!

**Comment by enuchi** [comment]
Ah, yes that makes sense! Should have mentioned it won't work in local development @poorawaste .

The repos that support the local development environment could actually be modified to support `google.script.host.editor.focus()`, but it would be a bit of work and don't think it's worth the trouble since they're probably not used much.  The only google client API that's been set up to work in local development is `google.script.run`.

See https://github.com/enuchi/gas-client and https://github.com/enuchi/Google-Apps-Script-Webpack-Dev-Server if you're interested in digging in to the internals.
